package com.avl.ditest.example;
 
public class ExampleMultipleRepositoryDeploy {
 
    public static void sampleMethod() {
      System.out.println("Sample method generated by maven Archetype..");
    }
 
}